### ISSUE TITLE
Demo Scene on iOS produces strange disturbance

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#232]
I build a test for iOS and get these strange patterns after a few minutes:
<img width="336" alt="Ohne Titel" src="https://user-images.githubusercontent.com/278428/56915141-15921c80-6ab6-11e9-8305-9bba930a4e30.png">

**Comment by huwb** [comment]
Thanks for reporting, thats interesting. While I'm not targeting iOS as a primary platform, this seems like an issue that should be fixed regardless.

**Comment by huwb** [comment]
One thing that might address this issue is to reduce the max sim timestep. Create Crest/Dynamic Wave Sim Settings in the project view and reduce the "Max Substep Dt" to something like 0.012 . This will mean the sim steps at 12ms or less instead of the default 16.67ms. At 30fps, it will do 3 steps. If necessary it could be reduced further.

The unfortunate byproduct of this is an extra sim step has to be done per frame, which will mean slightly more cost.

If anyone tries this and finds it adresses the issue, please post here.

**Comment by huwb** [comment]
Oh this should be resolved on latest on master branch here. Apologies i forgot to confirm.
