### ISSUE TITLE
Waves not showing up

### ISSUE THREAD

**Issue by Chadedala** [crest-ocean/crest#301]
**Describe the bug**
Waves not appearing. Both in editor and standalone build.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/939901/62424501-fd690500-b683-11e9-9a8f-d8415196e9ff.png)

**Log**
No errors in Editor log.

**Versions**
Version: Unity Standard Builtin Render Pipline, no HDRP no LWPR
Unity Version 2018.4.4.f1
Zip file was downloaded 24th July 2019 , so it was probably commit 6a6805e . (Huw: I tried it and it worked fine on my laptop).

**To Reproduce**
I start Unity, import the Package, no waves.

**Platform**
In editor. 
Build modules active for Mac, Linux, Windows and WebGL.

**Hardware**
GTX 1080 SLI
Driver Version : 22.21.13.8205

CPU 2x Intel I 7 6800 k
System Memory 64 GB.
Operation Software: Windows 8.1

**Misc information**
Other data types seem to work:
![image](https://user-images.githubusercontent.com/939901/62424799-c1846e80-b688-11e9-9d31-49cbbb5df38a.png)

**Comment by huwb** [comment]
Just realised - which package are you importing? We don't maintain packages on this site anymore due to time constraints, the last package is from quite some time ago now.

The way the github version is installed is by using the "Clone or download" button on the main page. You'll find the core crest files and the example content here: https://github.com/crest-ocean/crest/tree/master/crest/Assets/Crest

**Comment by huwb** [comment]
Just bumping this in case you have more info for us.

**Comment by huwb** [comment]
From discord discussion: Zip file was downloaded 24th July 2019 , so it was probably commit 6a6805e376a094aa09a2290e06967d6df7b00264

**Comment by huwb** [comment]
From a windows 7 setup:

![image](https://user-images.githubusercontent.com/939901/62425049-8e8faa00-b68b-11e9-8757-c05c89529363.png)

Windows 7 stock,
Graphic Card; GTX 750
Driver Version : 26.21.14.3039
Problem the same. So: This is current build from Github ( I download some Minutes ago ) 
Main Demo Scene, also no waves, same Problem with slider.
oh, systemMemory 8 GB

**Comment by huwb** [comment]
I sent a build made from my laptop, result is the same:

![image](https://user-images.githubusercontent.com/939901/62425211-7db55780-b6d0-11e9-9834-f1d398b3c533.png)

**Comment by huwb** [comment]
I had another report of this occurring for discord user Ugaitz. 

Intel HD Graphics 4000
intel i5-3320M cpu
4gb ram
Windows 10 Pro

this user repro'd it on version 7.0.0 from github - 27th Feb 2010

![image](https://user-images.githubusercontent.com/939901/62655739-8caf3a80-b95a-11e9-9e70-4846b7e71b0f.png)

**Comment by huwb** [comment]
@moosichu 

Currently we have:

GPU: GTX 1080, HD Graphics 4000, GT 650 M, GTX 750
CPU: 2X Intel i7 6800 k, i5-3320M, ?, ?
RAM: 64gb, 4gb, ?, 8gb
Windows: 8.1, 10 Pro, 10, 7

Repro'd before and after compute / TA additions.
Likely all DX11, but that really shouldnt matter

**Comment by moosichu** [comment]
https://github.com/huwb/crest-oceanrender/files/3342958/CrestIssue279.zip

Renderdoc capture from #279 as well. For reference.

**Comment by huwb** [comment]
Hi @Chadedala , we had 2 more reports of this bug in the last few days. I made an effort to consolidate what we have in one place, could you please follow this issue for updates: https://github.com/crest-ocean/crest/issues/279

We believe this to be a unity bug which we're working to confirm.

In the meantime we're looking at alternatives, the main one being reverting the core of Crest to an older state. This would be a shame but we don't seem to have many options.

I've linked this bug to #279, and will now close it as a duplicate so that we don't spread information/findings over multiple bugs. Hopefully that's ok for you.
