### ISSUE TITLE
No Animated Waves in Android Build for Oculus Quest

### ISSUE THREAD

**Issue by MR-Alex42** [crest-ocean/crest#332]
**Describe the bug**
Animated Waves work in the Unity Editor but not in the Android build for Oculus Quest.

**Screenshots / video**
Screenshot from Quest:
![de algro questcrest-20190825-161857 2](https://user-images.githubusercontent.com/15617301/63651402-97d4d980-c754-11e9-8f57-8039df79e60c.jpg)
For comparison a screenshot from the editor:
![image](https://user-images.githubusercontent.com/15617301/63651431-f26e3580-c754-11e9-9bef-8d549da8de3f.png)

**Log**
No errors shown in Log.

**Versions**
Render pipeline : Built-in
Unity: 2019.1.2f1

**To Reproduce**
Can provide project and APK if helpful.
Are you able to reproduce the issue in the example content/scenes?
I can reproduce the issue with a VR enabled main demo scene.

**Platform**
 - Android

**Hardware**
Oculus Quest (Snapdragon 835 chipset, Adreno 540 GPU, 4 GB RAM.

**Additional context**
Maybe the wave shader is not working correctly on the target hardware.
I used multipass as stereo rendering mode in the XR settings.
Forward rendering pipeline.

**Comment by moosichu** [comment]
Just to be clear, dynamic waves specifically refer the waves generated by dynamic objects like boats and are simulated at runtimes.

The screenshots you have posted seem to specifically refer show a lack of animated waves, which are the global deterministic waves found in the main Crest demo scene. Is that what you mean instead?

**Comment by MR-Alex42** [comment]
Yeah, you are right. I meant animated waves. Sorry for the wrong terminology. I've changed the issue headline and text accordingly.

**Comment by huwb** [comment]
Thanks for reporting @MR-Alex42 . This is a known issue unfortunately. I made an effort to consolidate what we have in one place, could you please follow this issue for updates: https://github.com/crest-ocean/crest/issues/279

We believe this to be a unity bug which we're working to confirm.

In the meantime we're looking at alternatives, the main one being reverting the core of Crest to an older state. This would be a shame but we don't seem to have many options.

I've linked this bug to #279, and will now close it as a duplicate so that we don't spread information/findings over multiple bugs. Hopefully that's ok for you.

**Comment by huwb** [comment]
Thanks for reporting @MR-Alex42 . This is a known issue unfortunately. I made an effort to consolidate what we have in one place, could you please follow this issue for updates: https://github.com/crest-ocean/crest/issues/279

We believe this to be a unity bug which we're working to confirm.

In the meantime we're looking at alternatives, the main one being reverting the core of Crest to an older state. This would be a shame but we don't seem to have many options.

I've linked this bug to #279, and will now close it as a duplicate so that we don't spread information/findings over multiple bugs. Hopefully that's ok for you.

**Comment by MR-Alex42** [comment]
Fine for me. Thanks.
