### ISSUE TITLE
Planar reflection lerp causes negative values

### ISSUE THREAD

**Issue by jjxtra** [crest-ocean/crest#334]
Planar reflection lerp goes out of bounds. The fix is changing line 33 of `OceanReflection.hlsl` to:

`io_colour = lerp(io_colour, refl.rgb, saturate(refl.a));`

Screenshot of problem showing subtractive effect:

![image](https://user-images.githubusercontent.com/1271832/64189296-31754880-ce31-11e9-81fb-ab8dfbbebb3f.png)

**Comment by jjxtra** [comment]
Fixed version, looks VERY NICE :)

![image](https://user-images.githubusercontent.com/1271832/64189389-5c5f9c80-ce31-11e9-9327-f142720e28f9.png)

**Comment by huwb** [comment]
Thanks for reporting that issue, and bonus points for also fixing it, and double bonus points for the beautiful screen shot :). I'll report back with updates

**Comment by jjxtra** [comment]
Thank you for making crest MIT license, it is becoming the standard for ocean on Unity.

**Comment by huwb** [comment]
Absorbing this now.. Yeah i always assumed the alpha value would be 0-1. I'm too curious - why is it outside of this range, is this something from Enviro or is it something on my side, do you know?

**Comment by jjxtra** [comment]
This is Weather Maker, and I don't have any changes to the code other than a planar reflection script which is reflecting my sun and skybox.

**Comment by cowhunt** [comment]
Could your sun/skybox be outputting alpha values that are outside 0-1? Is that intentional or required? I haven't encountered this before.

I can clamp it if needed, but just trying to understand if this is a data fix rather than adding instructions to the runtime..

**Comment by huwb** [comment]
Could your sun/skybox be outputting alpha values that are outside 0-1? Is that intentional or required? I haven't encountered this before.

I can clamp it if needed, but just trying to understand if this is a data fix rather than adding instructions to the runtime..

**Comment by jjxtra** [comment]
My skybox and sun are based off of https://github.com/SlightlyMad/AtmosphericScattering

**Comment by huwb** [comment]
Weird - i looked at the source and i dont see a reason why that stuff would output an alpha larger than 1. Is there any chance you could do a test with Weather Maker clamping its alpha output? I'd like to figure out what the problem is here (it could be a symptom of something else that is broken) rather than adding a clamp, and adding to the runtime, if you'd be willing to run that test?

**Comment by jjxtra** [comment]
I believe it is a negative alpha problem. Did you check for that? I will do a test on my end too

**Comment by huwb** [comment]
Oh sorry, I've confused matters thinking it might be greater than 1, because negative values of alpha are nonsense and wet should fix it. I definitely didn't see a reason the scattering code would output negative alpha values.

So I'd like to understand where such negative values are coming from and fix it at the source. I think the sky should always set a constant alpha value of 1 probably?

**Comment by huwb** [comment]
Yes could it always output 1 in the alpha, then the lerp above will take its value.

If you do so and find there's still issues, let me know as there might be another problem on our side.

**Comment by huwb** [comment]
Checking inactive issue.. did you end up getting more insight into if/why the sky is worrying negative alpha values?

**Comment by jjxtra** [comment]
For your purposes I would say go ahead and close it, I will leave the saturate call in my fork.

**Comment by huwb** [comment]
Ok thanks
