### ISSUE TITLE
How come _ShorelineFoamMinDepth is not generating foam by the shore?

### ISSUE THREAD

**Issue by EcoEditor** [crest-ocean/crest#374]
Cannot trace the function that calls SampleFoam(...) in the Ocean.shader
`
#if _FOAM_ON
SampleFoam(_LD_TexArray_Foam, uv_slice_smallerLod, wt_smallerLod, o.foam_screenPosXYW.x);
					#endif
`

I've looked at OceanFoam.hlsl and OceanHelpers.hlsh
It seems that there is a way to add foam effect on the shore, using: `_ShorelineFoamMinDepth("Shoreline Foam Min Depth", Range(0.01, 5.0)) = 0.27` 
Something that will resemble the image (taken from [here](https://www.needpix.com/photo/198099/rocks-crashing-waves-foam-shore-ocean-sea-water-wave-coast)):

![foam on rocks](https://user-images.githubusercontent.com/42212240/70908510-fc71b800-2013-11ea-80da-c7df6458765f.jpg)

However in my scene I don't have any generated foam around the shore, so this variable seems to not work. How come?

How do I get this effect, posted in issue #10?
![image](https://user-images.githubusercontent.com/42212240/70921727-8a0dd180-202d-11ea-8932-f807c5beb6a2.png)

Thank you

**Comment by huwb** [comment]
I guess it's either some kind of hardware bug, or a scene setup issue.

To rule out the first, do you have foam in the example scenes?

For the second, theres a section in the user guide dedicated to shorelines, and a video as well: https://www.youtube.com/watch?v=jcmqUlboTUk . The main component is a depth cache to identify where water is shallow.

In order to help more i'd need the fields from the issue template - what version you're using, what you're seeing, etc.

**Comment by EcoEditor** [comment]
Thank you very much for your response @huwb, it helped me a lot, and the video is very helpful as well. BTW I'm using unity 2018.4.4f1, it's working well.
It solved my issue. 

Cheers

**Comment by huwb** [comment]
Ok great
