### ISSUE TITLE
Flow not working in HDRP standalone builds

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#439]
**Describe the bug**
Flow doesn't work in standalone builds as it does in the editor.

**Screenshots / video**

![Flow Issue HDRP](https://user-images.githubusercontent.com/5249806/76401875-af18a300-63d6-11ea-8345-4e328da99ed1.jpeg)
HDRP showing the issue

![Flow Issue URP](https://user-images.githubusercontent.com/5249806/76401895-b6d84780-63d6-11ea-9ca8-64a679e4fbf6.jpeg)
URP for comparison

**Log**
MacOS [Player.txt](https://github.com/crest-ocean/crest/files/4317291/Player.txt)

**Versions**
2019.3.3f1 HDRP 7.2.1

**To Reproduce**
Make a build with the whirlpool scene and run.

**Platform**
 - Standalone
 - Windows and MacOS

**Hardware**
- Windows: 8700k + 2080 Ti
- MacOS: 8500B + RX580

**Additional context**
The LODs do look different between the two. But I am not sure what is happening. I also tried adding a fixed flow direction to the main scene for testing but it didn't work in standalone either.

**Comment by huwb** [comment]
Finally getting around to this. I'm getting the same thing issue here on my dell xps 15, also nothing of interest in my log.

This is pretty weird, flow is one of the simpler LodData's that we have so i'm not really sure whats going on there. Foam is clearly being advected by the flow.

I thought maybe the keyword for flow is not working or is getting knocked out for some reason, but it looks identical to the FOAM keyword and its definitely enabled on the material.

I did a renderdoc capture and i'm not sure the flow data is being bound to the pixel shader when rendering the surface, i could not see it in the list of inputs. There were no warnings or errors in renderdoc.

Thats as far as i got for now, will contemplate what the next move is!

**Comment by daleeidd** [comment]
I have found the cause of the problem.

Despite the Flow checkbox being enabled on the material, the `CREST_FLOW_ON` was missing in the `m_ShaderKeywords` list. It looks like it was accidentally removed in [77b38c8657d](https://github.com/cowhunt/crest-srp/commit/77b38c8657db450526ab4f7678ae203a246ba8f8).

It worked in the editor because on the `LodDataMgrFlow` we are enabling the keyword in the `OnEnable` event. But it didn't work in standalone because Unity strips out the flow variant of the shader since it is missed by Unity's heuristics for inclusion.

The article _[Stripping Scriptable Shader Variants](https://blogs.unity3d.com/2018/05/14/stripping-scriptable-shader-variants/)_ describes possible approaches to keeping the variant using scripting. We would have to go through all the scenes that are being included in the build and checking if flow is enabled on the ocean renderer.

Alternatively, we should not enable keywords in scripting and leave it up to the user to manage.

**Comment by huwb** [comment]
Sooo it took me way too long to realise - i think that define is enabled in the c#, not for the ocean surface material, but for the shape combine shader, which has this old define in it: `_FLOW_ON`

`#pragma multi_compile __ _FLOW_ON`

This is the one thats supposed to be turned on by code, and its a multi compile so it will work at runtime. I think this needs fixup now - looking at the whirlpool scene, the waves are not advected anymore, because that define _FLOW_ON doesnt match CREST_FLOW_ON. could you maybe search for any defines that have 'flow' in them and make them CREST_FLOW_ON?

I think the original intention with the material is that the define is added manually, by the user. You're right though - the c# does turn it on on the material. which is a conflict that i never realised.

Interesting idea with the stripping. i worry about edge cases. maybe the user has multiple materials in a Resources folder. maybe they want to distribute new ocean materials in an asset package, etc. I think this might end up being a bit of a spiders nest.

I'm tempted to unconflict them by making a new define `CREST_FLOW_ON_INTERNAL` and turning that on by c#, and then leaving the user to turn it on on the material. Then their results in editor should match in build. What do you think?

Does this make sense? Quite a lot to unpack i guess, let me know if i can expand on something.

**Comment by daleeidd** [comment]
I have applied your fixes. Looks much better now.

The `CREST_FLOW_ON_INTERNAL` keyword is a good idea. They are already separate in SG because we are using local keywords, but it would make its usage more clear.

Just wondering what you think about this:
> Or we could do the inverse of what we are doing now and check the material to enable the simulations in the ocean renderer. We could remove most of the toggles from the ocean renderer. Would reduce double authoring. We could also remove a lot of the keyword validation checks too.

One downside I can think of is for debugging purposes. Although we could move them under the debug header as overrides.

**Comment by huwb** [comment]
Nice

Oh I missed that - yes that's interesting. Can we reliably check the keywords on the material - I guess so? Agreed regarding overrides.

I guess one question is if all loddatas have corresponding keywords - I don't think sea floor depth has, but this could stay a toggle defaulted to on. Same for anim waves.

Dynamic waves doesn't either. It's possible this could be built up on demand (I guess based on register scripts?). Maybe that's an alternative angle here, create when inputs are present? Maybe the approach depends on the loddata.

The other thing is that ocean materials can change at runtime so this would need to to be handled and might require changes, and might have edge cases.

**Comment by daleeidd** [comment]
> Can we reliably check the keywords on the material - I guess so?

I believe so. I just test and it seemed fine.

> Maybe the approach depends on the loddata

Yes. This is certainly the case

> The other thing is that ocean materials can change at runtime so this would need to to be handled and might require changes, and might have edge cases.

So I guess it comes down to whether we can enable and disable simulations at runtime reliably. And whether we can do it without any significant overhead. Probably better spending time on other things. I'll create a task for it in long term for exploring it further.

**Comment by daleeidd** [comment]
This has been resolved.

**Comment by huwb** [comment]
Yeah in 4.1. thanks for this!
