### ISSUE TITLE
Height Queries in FixedUpdate no longer work with VSync disabled

### ISSUE THREAD

**Issue by skaughtx0r** [crest-ocean/crest#523]
**Describe the bug**
A recent change (501680bb6977d45c4ee45ce1ea354cee8dabead1) in QueryBase to clear guids makes it so height queries are now bound to the game's frame rate. If the frame rate is really high, all of the height queries in the FixedUpdate loop get returned as 0.

**Versions**
Crest: master branch
built-in render pipeline
Unity 2018.4.10f1

**To Reproduce**
Open the crest project, load threeboats scene. **Disable vsync** in the ProjectSettings -> Quality. This mostly seems to happen if the frame rate is well above 60fps.

**Platform**
 - Happens in both editor and standalone, the higher the framerate, the more likely it is to happen.
 - Platform: Windows

**Hardware**
GPU: NVIDIA RTX 2080

**Comment by huwb** [comment]
Sorry no reply before now.

Yeah this is potentially a thorny one. I realised im relying pretty heavily on the async gpu readback getting the queries back each frame. i can imagine that if gpu and cpu are free to update at different rates, results may not come back in a frame. With the latest version, guids are cleared each frame so it depends on results coming back every frame.

Ideas:
* Not support turning off vsync (?)
* Put the guid clearing on a optional switch, so it can at least be worked around. will leak guids when this switch is turned on.
* Instead of clearing the guids and flipping query registers etc on update, flip on QueryBase.DataArrived() instead. this might be a significant change. I dont have time now to look into it.

Let me know your thoughts for now..

**Comment by huwb** [comment]
I tried the third point in a test branch - commit referenced above. would you be up for trying it? its a hack but would be interested to know if it helps.

**Comment by skaughtx0r** [comment]
Yeah, I'll try it out, thanks!

**Comment by skaughtx0r** [comment]
@huwb This seems to work correctly in the Crest threeboats scene now. Unfortunately, I'm having some issues testing with my game because I'm using the `feature/post-proc-underwater-2` branch. Merging this branch into that has some file conflicts that I'm not completely sure how to resolve.

**Comment by skaughtx0r** [comment]
@huwb curious what's the status on this? It seemed like the changes fixed it for me.

**Comment by huwb** [comment]
We've had this issue reported by someone else. Need to get this fixed.

I don't feel good about what is prototyped in this branch. The steps to clean it up are not clear. And I don't feel flipping on DataArrived is robust. What if a query fails for whatever reason, seems like that could make the system grind to a halt.

I think making the system explicitly handle the case where results did not come back during a frame (so not clear guids) is a simpler and safer approach. Will try this out when I can..

**Comment by huwb** [comment]
Ok think i have a good fix for this now. PR #574

**Comment by huwb** [comment]
Will be fixed in 4.4

**Comment by daleeidd** [comment]
4.4 has been released which has the fix for this. Please reopen if this is still an issue.
