### ISSUE TITLE
Peristent little waves even with all spectrum pushed to 0

### ISSUE THREAD

**Issue by VizzzU** [crest-ocean/crest#542]
As the title says there is persistent little waves even with all sliders pushed to 0.

Keep hard work guys ! ( with the particle fx ? ... :) )

**Comment by daleeidd** [comment]
![1](https://user-images.githubusercontent.com/5249806/84566873-fb99c300-adb7-11ea-9840-0f503a63eeb0.jpg)

Thanks for reporting. Is this what you are seeing? All spectrum component sliders at 0 but the spectrum weight is at 1.

**Comment by ftejada17** [comment]
Hi @VizzzU and @daleeidd !! You mean with this problem that I opened ( https://github.com/crest-ocean/crest/issues/519#issue-623875617 ), in which the waves produced by the shader normals are those that exist in motion when all the waves of the spectrum are at 0?

In this video I have all the waves of the spectrum at 0 but there are still ripples in the water that move due to the Crest Shader Normal ...
https://youtu.be/byi7G2PXrxk

Regards

**Comment by VizzzU** [comment]
@ftejada17 ,  that's it ! I m sorry   I use to check issues posts before pushing one but i ve missed yours . Think that @daleeidd  Can close this one

**Comment by huwb** [comment]
I think there are 2 ways to interpret the above issue.

@daleeidd i think you have identified one issue in your screenshot, this is the issue i would think of when reading this title. i think we should fix this. I think its a case of extending the min spectrum power range, it was laziness/dodginess on my part that the above is happening. The min power is not low enough to stop short wavelengths appearing :/. If you do look at it, it would be good to verify that no waves are rendering - `HasWaves` should be false after the update function is called (`_gerstner.UpdateBatch(this, _batchIndex);`), if all sliders are set to min values.

the second interpretation which i think is referred to in 519 is connecting the normal maps to the spectrum values, it would be cool if the strength of the normal maps were connected to the spectrum values, so that when you turn down the spectrum the normal maps also go away. i guess they could be keyed off whatever spectrum values are below the current lowest LOD scale (i.e. if the current lods have waves down to 1m wavelength, the normal maps are keyed off the 0.5m wavelength spectrum slider?). it could be interesting to experiment with this to see if it works or not. what are your thoughts?

**Comment by daleeidd** [comment]
> I think its a case of extending the min spectrum power range

Sounds good.

**Comment by huwb** [comment]
Fix proposed in referenced PR
