### ISSUE TITLE
Report wave forces to DWP2

### ISSUE THREAD

**Issue by olavrv** [crest-ocean/crest#566]
Would be great if wave forces could be reported to for example DWP2, so that wave impacts affect floating objects with appropriate force.

**Comment by huwb** [comment]
I've been mulling this over. I think it probably does, because the wave forces come from buoyancy forces.

But I don't think we get the full richness of a real fluid impacting the side of a vessel, everything is a 2D approximation.

I'm not quite sure where to go with this. If you have a particular example of where it is currently breaking down it would be useful to make this a bit more concrete.

**Comment by olavrv** [comment]
@huwb I am not sure either. It is not a must, would just be a nice feature for more realistic scenarios. I guess it is relatively complex to achieve a realistic result, as the volume of water and velocity would have to be taken into consideration  for it to be realistic.

**Comment by huwb** [comment]
The buoyancy forces will account for displaced volume, and the velocities generate drag forces.

I guess if waves crashed against the side it would generate different forces.

I think this is sufficiently vague to close - but I'll keep thinking about it and will get notifications if you post in the future.
