### ISSUE TITLE
Question: Is it possible to sample heights with maximum detail level?

### ISSUE THREAD

**Issue by furkandinc** [crest-ocean/crest#578]
I looked at the documents and digged up in the code and could find any solution. I am doing a simulation software that ship movements should be simulated realistically. Thanks to Crest, it helped me a lot to make realistic wave simulation. There is no problem when camera and ship are close, ship being simulated well in this case. But when I place my camare to a distant place the lod area, ship is placed in, becomes higher lod level which is not detailed. I know Crest is desinged this way to get high fps while not using too much memory.
My question is it possible to sample height without using generated lod data from gpu? If this is possible, I would be simulate distant objects like they are close to main camera.
What do you think about this problem? Is it possible? Will it kill fps? Will it use too much memory?

**Comment by huwb** [comment]
In the Animated Waves Settings (if you create an asset an attach it to the ocean gameobject) you can set the collision source to Gerstner and it will compute heights on the cpu, outside of the LOD backbone. There is a burst-job version prototyped in a dev branch: https://github.com/crest-ocean/crest/pull/157

The problem is that the shape is nontrivial. For example shallow water dampens the waves in nontrivial ways, and the cpu does not know about the sea depths. So this would only work in open water and would not support general ocean inputs that affect the shape.

The other note is that visually the surface is LOD'd. I've had problems in the past if a detailed collision is used but a LOD'd surface is visually rendered - it looks like the boats are flying, or sinking into the water, and its not good..
