### ISSUE TITLE
Skybox not found, although set.

### ISSUE THREAD

**Issue by andrew-sidereal** [crest-ocean/crest#632]
**Describe the bug**
I'm using Enviro Sky & Weather -- it sets the skybox material. I can verify in Scene mode it is set. In play-mode it is still set both at the initial menu screen and then in the play scene. Yet, I'm receiving a warning about Crest not finding the skybox. Also, coloring does look to be incorrect. Screenshots of all below.

**Screenshots / video**
Here are shots of each step: https://imgur.com/a/MIVTcLj

**Log**
Validation: There is no skybox set in the lighting settings window. Ocean colour will be incorrect. Alternatively, try the Procedural Sky or Override Reflection Cubemap option on the ocean material. Click this message to highlight the problem object.
UnityEngine.Debug:LogWarning(Object, Object)
Crest.ValidatedHelper:DebugLog(String, MessageType, Object) (at Assets/Crest/Scripts/OceanValidation.cs:49)
Crest.OceanRenderer:Validate(OceanRenderer, ShowMessage) (at Assets/Crest/Scripts/OceanRenderer.cs:1101)
Crest.OceanRenderer:OnEnable() (at Assets/Crest/Scripts/OceanRenderer.cs:311)

**Versions**
Built-in

**Platform**
PC - Windows

**Comment by andrew-sidereal** [comment]
Here's a screenshot of the Ocean settings, in case it helps: https://i.imgur.com/KIS7mbx.png
This is a branch of Master as of Aug 12th.

**Comment by daleeidd** [comment]
Thank you for reporting. The ocean looks correct. It appears to be a false positive. My guess is the Enviro sets the skybox in play mode. Looking at the screenshots, the skybox is set for the menu scene. Is it possible that when you change scenes there is no skybox briefly before Enviro sets it up?

**Comment by andrew-sidereal** [comment]
Very odd. Okay, well thank you for verifying. The water looks awfully blue in those screenshots I added, when the sky is all reddish pink. Should that be adjusted automatically or is the base blue color of the water a constant and it's just the reflections/lighting which changes?

**Comment by daleeidd** [comment]
Those colours are determined by the colours on the ocean material. The sun and sky contribute colours as reflections.

> is the base blue color of the water a constant and it's just the reflections/lighting which changes?

That is pretty much correct.

On a second look, the last screenshot in the gallery doesn't look right. Whenever you see black where the skybox colour should be, then that is normally something wrong. Being a darker scene, it is a bit harder to tell though. If you look at the other screenshots, you will notice a lighter colour on the ocean surface which is very similar to the skybox colour closer to the horizon.

Have you tried running the ocean validator in edit mode? Since it seems to only be a problem with play mode, have you tried launching directly into the scene with Crest?

**Comment by daleeidd** [comment]
I'll close this for now due to inactivity. Let me know if the issue persists. I'll see the reply.
