### ISSUE TITLE
'Follow Horizontal Motion' not working (on dynamic waves from player boat in boat.unity)

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#666]
**Describe the bug**
If i run boat.unity, part of the wake from the players boat meanders around and is detached. I looked into it for a while and it appears that something is going wrong with the displacement queries. If i disable the other boats it fixes it.

**Versions**
2019.4.1, editor

**To Reproduce**
Play boat.unity in editor.

**Platform**
Editor, win64

**Comment by emaber** [comment]
Hi. We finally had the time to look into this and here's an update: 

Our problem was slightly different as described in an earlier email where you pointed me here, but I believe the root cause is the same.

I'll take as example the "FoamAddFromTex.shader" but it's the same in the other shaders for DynWaves.

If a set of objects share the same material the variable "_DisplacementAtInputPosition" is overwritten and all objects will render with the last value written, which will be correct only for one of the objects. The other objects will have an incorrect displacement.

A simple workaround is to use a different instance of the Material for every object. This works in our scenario and I suspect would work for you too.

Not sure if you want to pass this as a requirement or if you would like to have a more elegant solution.

**Comment by huwb** [comment]
OOPS. Thanks for this. Created the above PR ^

**Comment by huwb** [comment]
Merged thanks again @emaber
