### ISSUE TITLE
Achieve underwater effect when using "Set Water Height to Geometry"

### ISSUE THREAD

**Issue by adamthedorsey** [crest-ocean/crest#674]
How difficult would it be to show the underwater effect when using the "Set Water Height to Geometry" shader?

Or to not have so much pulling of the waves vertically?

<img width="807" alt="Screen Shot 2020-10-24 at 5 15 40 AM" src="https://user-images.githubusercontent.com/63333236/97078154-ffd0bb00-15b7-11eb-9a82-9c8f241cfa39.png">

I am trying to have an underwater "observatory" - which you can then swim into. I'd like it clear, almost like an aquarium.

<img width="971" alt="Screen Shot 2020-10-24 at 5 17 35 AM" src="https://user-images.githubusercontent.com/63333236/97078181-3b6b8500-15b8-11eb-873e-ce0325e86bb2.png">

Great tool BTW, worth every penny!

**Comment by daleeidd** [comment]
It sounds like you want a wall of water. There is work being done towards underwater windows which sounds like what you want. See #462 

As for a workaround. I don't think there is any good solution for that at the moment. You would probably be better off using the clip shader to cut out your observatory and disable the underwater effect. And then create your own solution for the water wall like a transparent material that mimics the underwater effect. Then make a transition as you enter the water so that it isn't noticeable.

**Comment by adamthedorsey** [comment]
This is what I’m looking for 100%. Thank you!
  
  
  
 For now I have a solution as you mentioned but this would be a lot more seamless and easier to maintain for me.
  
  
  

  
>

**Comment by daleeidd** [comment]
No worries. It will be a while away. We have to merge in the underwater post processing effect first. I'll close this one for now.
